### ISSUE TITLE
Duplicate entry in ICS

### ISSUE THREAD

**Issue by SpirytoPL** [notthehiddenwiki/NTHW#2]
https://github.com/notthehiddenwiki/NTHW/blob/main/Red%20Team/ICS/articles.md

Duplicate entry 18 and 20.

**Comment by notthehiddenwiki** [comment]
Fixed: [https://github.com/notthehiddenwiki/NTHW/commit/6c06f0632fbb36ea79ffdff0e770f8d9c1472fe9#diff-af49e34cf9e6abdb909d85053dfa2ddeeaa3fe47e450003270dc4594683adeb3](commit 6c06f06)

Thanks for letting me know!
